select 
"ISTAT_CODE",
"COMUNE_DES",
"CAP_CODE",
"REGIONE_DES",
"PROVINCIA_DES",
"POPOLAZIONE_NUM",
"SUPERFICIE_VL",
"POPOLAZIONE_NUM" / "SUPERFICIE_VL" as "DENSITA"
from comune
where "POPOLAZIONE_NUM" >= 30000 AND
LOWER("REGIONE_DES") LIKE '%lombardia%'
order by "POPOLAZIONE_NUM" desc
limit 10

